# Generated by Django 2.2.1 on 2019-05-30 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subdataset', '0004_subdataset_mongo_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subdataset',
            name='mongo_table',
            field=models.CharField(max_length=255),
        ),
    ]
