# Generated by Django 2.2.1 on 2019-05-30 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subdataset', '0005_auto_20190530_1852'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subdataset',
            old_name='mongo_table',
            new_name='mongo_collection_name',
        ),
    ]
