# Generated by Django 2.2.6 on 2019-10-21 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subdataset', '0007_columndataset_operations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subdataset',
            name='mongo_collection_name',
        ),
        migrations.DeleteModel(
            name='Operations',
        ),
    ]
