# Generated by Django 2.2.6 on 2019-10-21 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subdataset', '0008_auto_20191021_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='subdataset',
            name='label',
            field=models.CharField(default='', max_length=255),
        ),
    ]
