# Generated by Django 2.2.1 on 2019-05-21 18:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubDataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=255)),
                ('create_date', models.DateField(default=django.utils.timezone.now)),
                ('last_modified_date', models.DateField(default=django.utils.timezone.now)),
                ('size', models.FloatField(default=0)),
            ],
        ),
    ]
