# Generated by Django 2.2.1 on 2019-05-21 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subdataset', '0002_subdataset_dataset'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subdataset',
            name='size',
        ),
    ]
