# Generated by Django 2.2.6 on 2019-10-21 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subdataset', '0009_subdataset_label'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ColumnDataset',
        ),
    ]
