# Generated by Django 2.2.6 on 2019-10-26 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subdataset', '0010_delete_columndataset'),
    ]

    operations = [
        migrations.AddField(
            model_name='subdataset',
            name='raport_url',
            field=models.CharField(default='', max_length=255),
        ),
    ]
